'use strict';
(()=>{
const M=window.KATORT,$=id=>document.getElementById(id),colors=['#103c2e','#c49b50','#5c927b','#829288'];let english=false,year=2025,current='resumen';const done=new Set(),charts=new Map();
const t=(es,en)=>english?en:es,n=(v,d=0)=>new Intl.NumberFormat(english?'en-US':'es-MX',{maximumFractionDigits:d,minimumFractionDigits:d}).format(v),usd=v=>'USD '+n(v),ratio=v=>n(v,2)+'×',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.querySelectorAll('[data-en]').forEach(e=>e.dataset.es=e.innerHTML);
// Keep the reporting period available in every section of the reference.
document.querySelector('.notice').after(document.querySelector('.toolbar'));
const referenceLink=document.createElement('a');referenceLink.href='caso/';referenceLink.className='link';referenceLink.dataset.en='← Katort example case';referenceLink.dataset.es='← Caso de ejemplo Katort';referenceLink.textContent=referenceLink.dataset.es;document.querySelector('footer').append(referenceLink);
const publicNote=document.querySelector('.rail-note');publicNote.dataset.en='Public fictional reference. Never upload confidential client information here.';publicNote.dataset.es='Referencia pública ficticia. Nunca subir aquí información confidencial de clientes.';publicNote.textContent=publicNote.dataset.es;
function rows(id,data){$(id).innerHTML=data.map(([label,value])=>`<div class="metric-row"><span>${label}</span><strong>${value}</strong></div>`).join('');}
function kpis(id,data){$(id).innerHTML=data.map(([label,value,detail])=>`<article class="kpi"><span>${label}</span><strong>${value}</strong><small>${detail||''}</small></article>`).join('');}
function table(id,headers,data){$(id).innerHTML=`<table><thead><tr>${headers.map((h,i)=>`<th><button type="button" data-sort="${i}">${h} ↕</button></th>`).join('')}</tr></thead><tbody>${data.map(r=>'<tr>'+r.map(v=>`<td>${v}</td>`).join('')+'</tr>').join('')}</tbody></table>`;$(id).querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const body=$(id).querySelector('tbody'),idx=+b.dataset.sort,dir=b.dataset.direction==='asc'?-1:1;b.dataset.direction=dir===1?'asc':'desc';const parse=s=>Number(s.replace(/USD|[%×,\s]/g,''));[...body.rows].sort((a,c)=>{const x=a.cells[idx].textContent,z=c.cells[idx].textContent;return dir*(x.trim()!==''&&z.trim()!==''&&Number.isFinite(parse(x))&&Number.isFinite(parse(z))?parse(x)-parse(z):x.localeCompare(z));}).forEach(r=>body.appendChild(r));});}
// Native canvas charts: no remote libraries, fonts or services required.
function plot(id,labels,series,type='bar'){charts.set(id,{labels,series,type});const cv=$(id);cv.onmousemove=e=>{const bounds=cv.getBoundingClientRect(),i=Math.max(0,Math.min(labels.length-1,Math.floor((e.clientX-bounds.left-58)/(bounds.width-70)*labels.length)));cv.title=type==='donut'?labels.map((l,j)=>l+': '+n(series[0].values[j])).join(' · '):labels[i]+' · '+series.map(s=>s.name+': '+n(s.values[i])).join(' · ');};draw(id);}
function draw(id){const canvas=$(id);if(!canvas||canvas.closest('[hidden]'))return;const cfg=charts.get(id);if(!cfg)return;const w=canvas.parentElement.clientWidth,h=canvas.parentElement.clientHeight;if(!w)return;const dpr=window.devicePixelRatio||1;canvas.width=w*dpr;canvas.height=h*dpr;canvas.style.width=w+'px';canvas.style.height=h+'px';const c=canvas.getContext('2d');c.scale(dpr,dpr);c.font='12px Arial';c.fillStyle='#46554c';const {labels,series,type}=cfg;canvas.setAttribute('aria-label',series.map(s=>s.name+': '+labels.map((l,i)=>l+' '+n(s.values[i])).join(', ')).join('; '));
if(type==='donut'){let angle=-Math.PI/2;const total=series[0].values.reduce((a,b)=>a+b,0),r=Math.min(w*.25,h*.29),cx=w/2,cy=h*.37;series[0].values.forEach((v,i)=>{c.beginPath();c.arc(cx,cy,r,angle,angle+v/total*Math.PI*2);c.strokeStyle=colors[i%4];c.lineWidth=r*.45;c.stroke();angle+=v/total*Math.PI*2;});c.fillStyle='#103c2e';c.textAlign='center';c.font='bold 18px Arial';c.fillText(n(total),cx,cy+6);c.font='12px Arial';labels.forEach((l,i)=>{c.fillStyle=colors[i%4];c.fillRect(14,h-60+i*18,9,9);c.fillStyle='#46554c';c.textAlign='left';c.fillText(l+': '+n(series[0].values[i]),30,h-51+i*18);});return;}
const all=series.flatMap(s=>s.values),max=Math.max(1,...all)*1.12,min=Math.min(0,...all),left=58,right=w-12,top=28,bottom=h-48,x=i=>left+(i+.5)*(right-left)/labels.length,y=v=>bottom-(v-min)/(max-min)*(bottom-top);c.font='11px Arial';c.textAlign='right';for(let i=0;i<=4;i++){const v=min+(max-min)*i/4,yy=y(v);c.strokeStyle='#dce4dc';c.beginPath();c.moveTo(left,yy);c.lineTo(right,yy);c.stroke();c.fillStyle='#46554c';c.fillText(Math.abs(v)>=1000?n(v/1000)+'k':n(v),left-6,yy+4);}series.forEach((s,j)=>{c.fillStyle=colors[j%4];c.fillRect(left+j*140,8,9,9);c.textAlign='left';c.fillStyle='#46554c';c.fillText(s.name,left+14+j*140,17);c.strokeStyle=colors[j%4];c.fillStyle=colors[j%4];if(type==='line'){c.beginPath();s.values.forEach((v,i)=>i?c.lineTo(x(i),y(v)):c.moveTo(x(i),y(v)));c.lineWidth=2.5;c.stroke();s.values.forEach((v,i)=>{c.beginPath();c.arc(x(i),y(v),3,0,Math.PI*2);c.fill();});}else{s.values.forEach((v,i)=>{const bw=(right-left)/labels.length*.65/series.length;c.fillRect(x(i)-(series.length*bw)/2+j*bw,Math.min(y(v),y(0)),bw-2,Math.max(1,Math.abs(y(v)-y(0))));});}});c.textAlign='center';c.fillStyle='#46554c';labels.forEach((l,i)=>c.fillText(l.length>9?l.slice(0,8):l,x(i),bottom+18));}
const series=(name,values)=>({name,values});
function render(){const m=M.calculate(year),months=M.monthly(m),loan=M.debtSchedule(),b=M.balance,ca=b.cash+b.receivables+b.inventory+b.prepaids,cl=b.payables+b.accrued+b.currentDebt;
kpis('overview-kpis',[[t('Ventas','Revenue'),usd(m.revenue),t('Exportación + mercado local','Export + local market')],['EBITDA',usd(m.ebitda),n(m.margin*100,1)+'% '+t('margen','margin')],['DSCR',ratio(m.dscr),t('Caja / servicio de deuda','Cash / debt service')],[t('Caja al cierre','Closing cash'),usd(m.closingCash),String(year)]]);
rows('diagnosis',[[t('Caja tras pagar deuda','Cash after debt service'),usd(m.afterDebt)],[t('Servicio de deuda','Debt service'),usd(m.service)],[t('Meta interna de cobertura','Internal coverage target'),'1.30×']]);
plot('revenue-chart',[t('Exportación','Export'),t('Mercado local','Local market')],[series(t('Ventas','Revenue'),[m.exportRevenue,m.localRevenue])],'donut');rows('revenue-detail',[[t('Exportación','Export'),usd(m.exportRevenue)],[t('Mercado local','Local market'),usd(m.localRevenue)]]);
kpis('operations-kpis',[[t('Cosecha bruta','Gross harvest'),n(m.grossKg/1000)+' t',n(m.yield,1)+' t/ha'],[t('Exportable','Export grade'),n(m.exportShare)+'%',n(m.exportKg/1000,1)+' t'],[t('Precio exportación','Export price'),'USD '+n(m.price,2)+'/kg',t('Supuesto inventado','Invented assumption')],[t('Rechazo','Rejects'),n(m.reject)+'%',n(m.rejectKg/1000,1)+' t']]);
plot('harvest-chart',[t('Exportación (t)','Export (t)'),t('Local (t)','Local (t)'),t('Rechazo (t)','Rejects (t)')],[series('t',[m.exportKg/1000,m.localKg/1000,m.rejectKg/1000])],'donut');rows('harvest-detail',[[t('Kg comercializables','Saleable kg'),n(m.exportKg+m.localKg)],[t('Ingreso por hectárea','Revenue per hectare'),usd(m.revenue/100)]]);
rows('field-metrics',[[t('Agua anual','Annual water'),n(M.facts.annualWaterM3)+' m³'],[t('Agua / kg bruto','Water / gross kg'),n(M.facts.annualWaterM3/m.grossKg,2)+' m³/kg'],[t('Personal permanente / temporal','Permanent / seasonal staff'),'22 / 120'],[t('Días temporales','Seasonal days'),'110'],[t('Cobranza supuesta','Collection assumption'),t('45 días','45 days')],[t('Destino EE.UU. / Canadá','US / Canada destination'),'90% / 10%']]);
table('kpi-table',[t('Indicador','Metric'),t('Actual simulado','Simulated actual'),t('Meta interna','Internal target')],[[t('Rendimiento','Yield'),n(m.yield,1)+' t/ha','8.5 t/ha'],[t('Calidad exportable','Export grade'),n(m.exportShare)+'%','85%'],['DSCR',ratio(m.dscr),'1.30×'],[t('Mayor comprador','Largest buyer'),'50%','≤35%'],[t('Rechazo','Rejects'),'5%','≤4%']]);
rows('income',[[t('Ventas','Revenue'),usd(m.revenue)],[t('Costos variables','Variable costs'),usd(-m.variable)],[t('Costos fijos','Fixed costs'),usd(-m.fixed)],['EBITDA',usd(m.ebitda)],[t('Depreciación','Depreciation'),usd(-m.depreciation)],['EBIT',usd(m.ebit)],[t('Intereses','Interest'),usd(-m.interest)],[t('Antes de impuestos','Before tax'),usd(m.ebt)],[t('Impuesto ilustrativo','Illustrative tax'),usd(-m.tax)],[t('Utilidad neta','Net income'),usd(m.netIncome)]]);
rows('cashflow',[[t('Caja inicial','Opening cash'),usd(m.openingCash)],['EBITDA',usd(m.ebitda)],[t('Impuesto','Tax'),usd(-m.tax)],[t('Capital de trabajo','Working capital increase'),usd(-m.deltaWC)],[t('CAPEX','CAPEX'),usd(-m.capex)],['CFADS',usd(m.cfads)],[t('Intereses','Interest'),usd(-m.interest)],[t('Amortización capital','Principal repayment'),usd(-m.principal)],[t('Distribución propietario','Owner distribution'),usd(-m.dividends)],[t('Caja final','Closing cash'),usd(m.closingCash)]]);
const names=english?['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']:['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];plot('cash-chart',names,[series(t('Caja USD','Cash USD'),months.map(x=>x.cash))],'line');$('cash-warning').textContent=t('Mínimo mensual simulado: ','Simulated monthly minimum: ')+usd(Math.min(...months.map(x=>x.cash)))+'. '+t('El calendario es una distribución ilustrativa, no cobranza por factura.','This is an illustrative allocation, not invoice-level collections.');table('monthly-table',[t('Mes','Month'),t('Ventas','Revenue'),t('Operación','Operations'),t('Otros egresos','Other outflows'),t('Caja cierre','Closing cash')],months.map(x=>[names[x.month],usd(x.sales),usd(x.variable+x.fixed),usd(x.capex+x.wc+x.tax+x.interest+x.principal+x.dividends),usd(x.cash)]));
rows('balance',[[t('Caja','Cash'),usd(b.cash)],[t('Cuentas por cobrar','Receivables'),usd(b.receivables)],[t('Inventario','Inventory'),usd(b.inventory)],[t('Anticipos','Prepaids'),usd(b.prepaids)],[t('Activos fijos netos','Net fixed assets'),usd(b.fixedNet)],[t('Otros activos','Other assets'),usd(b.otherAssets)],[t('TOTAL ACTIVOS','TOTAL ASSETS'),usd(4100000)],[t('Proveedores + acumulados','Payables + accruals'),usd(b.payables+b.accrued)],[t('Deuda CP / LP','Current / long-term debt'),usd(b.currentDebt)+' / '+usd(b.longDebt)],[t('Capital + resultados acumulados','Capital + retained earnings'),usd(b.capital+b.retained)],[t('PASIVO + CAPITAL','LIABILITIES + EQUITY'),usd(4100000)],[t('Razón circulante','Current ratio'),ratio(ca/cl)],[t('Deuda neta / EBITDA 2025','Net debt / 2025 EBITDA'),ratio((1560000-b.cash)/M.calculate(2025).ebitda)]]);
plot('cost-chart',[t('Variables','Variable'),t('Fijos','Fixed')],[series('USD',[m.variable,m.fixed])]);const enCosts=['Labor','Inputs and nutrition','Water and energy','Harvest, grading and packing','Refrigerated freight','Other field costs','Land lease','Administration','Insurance','Operating maintenance','Quality and certification'];rows('cost-detail',[...M.variableCosts.map(([s,v],i)=>[t(s,enCosts[i]),usd(v*m.variable/1600000)]),...M.fixedCosts.map(([s,v],i)=>[t(s,enCosts[6+i]),usd(v*m.fixed/420000)])]);
kpis('debt-kpis',[[t('Principal original','Original principal'),usd(2600000),'2022'],[t('Saldo tras 4 pagos','Balance after 4 payments'),usd(1560000),t('Cierre 2025','2025 closing')],[t('Capital anual','Annual principal'),usd(260000),t('6 pagos pendientes','6 payments remaining')],[t('Pago 2026','2026 payment'),usd(338000),t('Interés USD 78,000','Interest USD 78,000')]]);plot('debt-chart',loan.map(x=>String(x.year)),[series(t('Saldo USD','Balance USD'),loan.map(x=>x.closing))],'line');plot('service-chart',loan.map(x=>String(x.year)),[series(t('Capital','Principal'),loan.map(x=>x.principal)),series(t('Interés','Interest'),loan.map(x=>x.interest))]);table('debt-table',[t('Año','Year'),t('Inicial','Opening'),t('Capital','Principal'),t('Interés','Interest'),t('Pago total','Total payment'),t('Final','Closing'),t('Estado','Status')],loan.map(x=>[x.year,usd(x.opening),usd(x.principal),usd(x.interest),usd(x.payment),usd(x.closing),x.paid?t('Pagado · supuesto','Paid · assumed'):t('Pendiente','Remaining')]));
const assetNames=['Owned agricultural land · 60 ha','Plantation establishment · 100 ha','Irrigation and pumping','Farm machinery','Packing and cold storage','Vehicles'];table('asset-table',[t('Activo','Asset'),t('Costo bruto','Gross cost'),t('Depreciación acumulada','Accumulated depreciation'),t('Neto','Net')],[...M.assets.map((a,i)=>[t(a.name,assetNames[i]),usd(a.gross),usd(a.depreciation),usd(a.net)]),[t('TOTAL','TOTAL'),usd(4000000),usd(890000),usd(3110000)]]);rows('rentals',[[t('Renta anual · 40 ha','Annual land lease · 40 ha'),usd(80000)],[t('Flete contratado anual','Annual contracted freight'),usd(160000)],[t('Ya incluidos en gastos','Already included in expenses'),t('No duplicar','Do not double count')]]);
const projections=M.projections();plot('projection-chart',projections.map(x=>String(x.year)),[series(t('Ventas','Revenue'),projections.map(x=>x.revenue)),series('EBITDA',projections.map(x=>x.ebitda))]);table('projection-table',[t('Año','Year'),t('Ventas','Revenue'),'EBITDA','CFADS','DSCR',t('Deuda cierre','Closing debt')],projections.map(x=>[x.year,usd(x.revenue),usd(x.ebitda),usd(x.cfads),ratio(x.dscr),usd(x.closingDebt)]));plot('buyer-chart',[t('Comprador A','Buyer A'),t('Comprador B','Buyer B'),t('Comprador C','Buyer C')],[series('%',[50,30,20])],'donut');
const risks=[[t('Precio -15%','Price -15%'),t('Alta','High'),t('Margen y cobertura','Margin and coverage'),t('Bandas de precio; diversificar','Price bands; diversify')],[t('Rendimiento -15%','Yield -15%'),t('Media','Medium'),t('Menor volumen','Lower volume'),t('Seguimiento por lote; reserva','Block tracking; reserve')],[t('Agua / bombeo','Water / pumping'),t('Media','Medium'),t('Interrupción cosecha','Harvest disruption'),t('Plan técnico y respaldo','Technical plan and backup')],[t('Cobranza retrasada','Delayed collection'),t('Alta','High'),t('Liquidez','Liquidity'),t('Límites crédito y cobranza semanal','Credit limits and weekly collections')],[t('Ruptura cadena fría','Cold-chain failure'),t('Media','Medium'),t('Rechazos','Rejections'),t('Trazabilidad temperatura','Temperature traceability')],[t('Concentración 50%','50% concentration'),t('Alta','High'),t('Pérdida de cliente','Customer loss'),t('Dos compradores adicionales','Two additional buyers')]];table('risk-table',[t('Riesgo ficticio','Fictional risk'),t('Probabilidad cualitativa','Qualitative likelihood'),t('Impacto','Impact'),t('Respuesta','Response')],risks);
renderActions();rows('model-checks',[[t('Balance: activos = pasivo + capital','Balance: assets = liabilities + equity'),t('Correcto · USD 4,100,000','Pass · USD 4,100,000')],[t('Cosecha = exportación + local + rechazo','Harvest = export + local + rejects'),t('Correcto','Pass')],[t('Caja anual = cierre mensual diciembre','Annual cash = December closing cash'),Math.abs(months[11].cash-m.closingCash)<.01?t('Correcto','Pass'):'ERROR'],[t('Deuda: último saldo = 0','Debt: final balance = 0'),loan[9].closing===0?t('Correcto','Pass'):'ERROR']]);resetScenario();}
function resetScenario(){const b=M.periods[year];['price','yield','cost'].forEach(id=>$(id).step='.01');$('price').value=b.price;$('yield').value=b.yield;$('quality').value=b.exportShare;$('cost').value=b.variablePerKg;$('diagnosis').previousElementSibling.textContent=t(`El periodo ${year} tiene cobertura de ${ratio(M.calculate(year).dscr)}: ${M.calculate(year).dscr<1.3?'por debajo':'por encima'} de la meta interna de 1.30×. Utilidad no equivale a caja disponible.`,`The ${year} period has ${ratio(M.calculate(year).dscr)} coverage: ${M.calculate(year).dscr<1.3?'below':'above'} the internal 1.30× target. Profit is not the same as available cash.`);scenario();}
function scenario(){const base=M.calculate(year),m=M.calculate(year,{price:+$('price').value,yield:+$('yield').value,exportShare:+$('quality').value,variablePerKg:+$('cost').value});$('price-value').textContent='USD '+n(m.price,2);$('yield-value').textContent=n(m.yield,1)+' t/ha';$('quality-value').textContent=n(m.exportShare)+'%';$('cost-value').textContent='USD '+n(m.variablePerKg,2);kpis('scenario-kpis',[[t('Ventas','Revenue'),usd(m.revenue)],['EBITDA',usd(m.ebitda)],['CFADS',usd(m.cfads)],['DSCR',ratio(m.dscr)]]);$('scenario-verdict').textContent=m.dscr<1?t('La caja no cubre el pago de deuda.','Cash does not cover debt service.'):m.dscr<1.3?t('Cubre deuda, pero no alcanza la meta interna de 1.30×.','Covers debt, but misses the internal 1.30× target.'):t('Supera la meta interna de cobertura de 1.30×.','Exceeds the internal 1.30× coverage target.');$('scenario-verdict').style.borderLeft='4px solid '+(m.dscr<1?'#a13434':m.dscr<1.3?'#94651c':'#103c2e');plot('scenario-chart',['EBITDA','CFADS',t('Deuda','Service')],[series(t('Base','Base'),[base.ebitda,base.cfads,base.service]),series(t('Escenario','Scenario'),[m.ebitda,m.cfads,m.service])]);rows('scenario-detail',[[t('Caja después de deuda','Cash after debt'),usd(m.afterDebt)],[t('Caja final','Closing cash'),usd(m.closingCash)],[t('Precio equilibrio EBITDA','EBITDA break-even price'),'USD '+n(m.ebitdaBreakEvenPrice,2)+'/kg']]);const prices=[-.4,-.2,0,.2,.4].map(d=>base.price+d),yields=[-1,-.5,0,.5,1].map(d=>base.yield+d);$('sensitivity').innerHTML='<table><thead><tr><th>t/ha ↓ / USD/kg →</th>'+prices.map(p=>'<th>'+n(p,2)+'</th>').join('')+'</tr></thead><tbody>'+yields.map(y=>'<tr><th>'+n(y,1)+'</th>'+prices.map(p=>{const d=M.calculate(year,{price:p,yield:y}).dscr;return `<td style="background:${d<1?'#f5dddd':d<1.3?'#fff0ce':'#ddede3'}">${ratio(d)}</td>`;}).join('')+'</tr>').join('')+'</tbody></table>';return m;}
const actions=[['30',t=>t('Separar reserva para servicio de deuda','Separate debt-service reserve'),'Finanzas / Finance',t=>t('Reservar USD 28,167 al mes en 2026; validar disponibilidad.','Reserve USD 28,167 monthly in 2026; validate affordability.')],['30',t=>t('Tablero de caja a 13 semanas','13-week cash forecast'),'Administración / Administration',t=>t('Actualizar cobranza, nómina y embarques cada semana.','Update collections, payroll and shipments weekly.')],['30',t=>t('Margen por embarque','Shipment contribution margin'),'Comercial / Sales',t=>t('Registrar calidad, rechazo y flete; no solo volumen.','Track quality, rejects and freight, not just volume.')],['60',t=>t('Diversificar compradores','Diversify buyers'),'Javier Ortiz',t=>t('Contactar dos compradores; meta de concentración ≤35%.','Contact two buyers; concentration target ≤35%.')],['60',t=>t('Reducir rechazo','Reduce rejects'),'Operaciones / Operations',t=>t('Meta interna 4%; revisar clasificación y cadena fría.','Internal 4% target; review grading and cold chain.')],['90',t=>t('Revisar regla de inversión','Review investment gate'),'Dirección / Management',t=>t('No expandir sin prueba de estrés y caja suficiente.','No expansion without stress test and adequate liquidity.')]];
function renderActions(){$('action-list').innerHTML=actions.map((a,i)=>`<article class="card action"><label><input type="checkbox" data-action="${i}" ${done.has(i)?'checked':''}><strong>${a[1](t)}</strong></label><p>${a[3](t)}</p><small>${t('Plazo','Due')}: ${a[0]} ${t('días','days')} · ${a[2]}</small></article>`).join('');$('action-list').querySelectorAll('input').forEach(e=>e.onchange=()=>{e.checked?done.add(+e.dataset.action):done.delete(+e.dataset.action);progress();});progress();}
function progress(){$('action-progress').textContent=`${done.size} / ${actions.length} `+t('acciones revisadas en esta sesión','actions reviewed in this session');}
function route(){current=location.hash.slice(1)||'resumen';if(!$(current)?.classList.contains('view'))current='resumen';document.querySelectorAll('.view').forEach(e=>e.hidden=e.id!==current);document.querySelectorAll('nav a').forEach(a=>{a.classList.toggle('active',a.hash==='#'+current);a.hash==='#'+current?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current');});requestAnimationFrame(()=>charts.forEach((v,id)=>draw(id)));}
$('period').onchange=()=>{year=+$('period').value;render();};$('lang').onclick=()=>{english=!english;document.documentElement.lang=english?'en':'es';document.querySelectorAll('[data-en]').forEach(e=>e.innerHTML=english?e.dataset.en:e.dataset.es);$('lang').textContent=english?'ES':'EN';$('lang').setAttribute('aria-label',t('Cambiar a inglés','Switch to Spanish'));$('period').options[0].text=t('2025 · cierre simulado','2025 · simulated closing');$('period').options[1].text=t('2026 · presupuesto ficticio','2026 · fictional budget');document.querySelector('.demo-pill').textContent=t('DEMO · DATOS FICTICIOS','DEMO · FICTIONAL DATA');const values=['price','yield','quality','cost'].map(id=>$(id).value);render();['price','yield','quality','cost'].forEach((id,i)=>$(id).value=values[i]);scenario();};['price','yield','quality','cost'].forEach(id=>$(id).oninput=scenario);document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{resetScenario();const p=M.periods[year],kind=b.dataset.preset;if(kind!=='base'){$('price').value=p.price*(kind==='stress'?.85:1.05);$('yield').value=p.yield*(kind==='stress'?.85:1.05);$('quality').value=p.exportShare+(kind==='stress'?-5:3);$('cost').value=p.variablePerKg*(kind==='stress'?1.10:.97);}scenario();});
function preparePrint(){document.querySelectorAll('.view').forEach(e=>e.hidden=false);charts.forEach((v,id)=>draw(id));}function finishPrint(){route();}window.addEventListener('beforeprint',preparePrint);window.addEventListener('afterprint',finishPrint);const print=()=>{preparePrint();requestAnimationFrame(()=>window.print());};$('print').onclick=print;$('export-report').onclick=print;window.addEventListener('hashchange',route);window.addEventListener('resize',()=>charts.forEach((v,id)=>draw(id)));render();route();
$('lang').addEventListener('click',()=>{referenceLink.href='caso/?lang='+(english?'en':'es');});
if(new URLSearchParams(location.search).get('lang')==='en')$('lang').click();
})();
