'use strict';
// Reproducible SYNTHETIC data. No observation below is a market quotation.
(function(root){
const mean=a=>a.reduce((s,v)=>s+v,0)/a.length,dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),quantile=(a,p)=>{const s=[...a].sort((x,y)=>x-y),i=(s.length-1)*p;return s[Math.floor(i)]+(s[Math.ceil(i)]-s[Math.floor(i)])*(i%1);};
function inverse(matrix){const n=matrix.length,a=matrix.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]);for(let j=0;j<n;j++){let p=j;for(let i=j+1;i<n;i++)if(Math.abs(a[i][j])>Math.abs(a[p][j]))p=i;if(Math.abs(a[p][j])<1e-11)throw Error('Singular design');[a[j],a[p]]=[a[p],a[j]];const v=a[j][j];a[j]=a[j].map(x=>x/v);for(let i=0;i<n;i++)if(i!==j){const f=a[i][j];a[i]=a[i].map((x,k)=>x-f*a[j][k]);}}return a.map(r=>r.slice(n));}
function ols(X,y){const n=X.length,k=X[0].length,xtx=Array.from({length:k},(_,i)=>Array.from({length:k},(_,j)=>X.reduce((s,r)=>s+r[i]*r[j],0))),inv=inverse(xtx),xty=Array.from({length:k},(_,i)=>X.reduce((s,r,j)=>s+r[i]*y[j],0)),beta=inv.map(r=>dot(r,xty)),fitted=X.map(r=>dot(r,beta)),residuals=y.map((v,i)=>v-fitted[i]),sse=dot(residuals,residuals),avg=mean(y),sst=y.reduce((s,v)=>s+(v-avg)**2,0),meat=Array.from({length:k},(_,i)=>Array.from({length:k},(_,j)=>X.reduce((s,r,h)=>s+r[i]*r[j]*residuals[h]**2,0))),cov=inv.map(r=>inv.map(v=>r.reduce((s,a,i)=>s+a*dot(meat[i],v),0)*n/(n-k))),se=cov.map((r,i)=>Math.sqrt(Math.max(0,r[i])));return {beta,se,n,k,fitted,residuals,inv,mse:sse/(n-k),r2:1-sse/sst,adjusted:1-(sse/(n-k))/(sst/(n-1)),dw:residuals.slice(1).reduce((s,v,i)=>s+(v-residuals[i])**2,0)/sse};}
let seed=20261001;function random(){seed=(1664525*seed+1013904223)>>>0;return seed/4294967296;}function noise(){return (random()+random()+random()+random()-2)*.12;}
const raw=Array.from({length:72},(_,i)=>{const month=i%12,year=2020+Math.floor(i/12),angle=2*Math.PI*month/12,income=100*Math.exp(.0025*i+noise()*.35),substitute=2.7*Math.exp(.0018*i+.07*Math.cos(angle+.4)+noise()*.4),price=3.55*Math.exp(.0021*i+.13*Math.sin(angle)+noise()),q=18000*Math.exp(-.75*Math.log(price/3.55)+1.15*Math.log(income/100)+.35*Math.log(substitute/2.7)+.18*Math.cos(angle)+noise());return {year,month,date:`${year}-${String(month+1).padStart(2,'0')}`,price,demand:q,income,substitute};});
const scale=4/mean(raw.filter(r=>r.year===2025).map(r=>r.price));const history=raw.map(r=>({...r,price:r.price*scale}));
const demandX=r=>[1,Math.log(r.price/4),Math.log(r.income/100),Math.log(r.substitute/2.7),Math.sin(2*Math.PI*r.month/12),Math.cos(2*Math.PI*r.month/12)],priceX=(r,i)=>[1,i/12,Math.sin(2*Math.PI*r.month/12),Math.cos(2*Math.PI*r.month/12)];
const demandFit=ols(history.map(demandX),history.map(r=>Math.log(r.demand))),priceFit=ols(history.map(priceX),history.map(r=>Math.log(r.price))),training=history.slice(0,60),holdout=history.slice(60),dTrain=ols(training.map(demandX),training.map(r=>Math.log(r.demand))),pTrain=ols(training.map(priceX),training.map(r=>Math.log(r.price)));
const smearing=fit=>mean(fit.residuals.map(Math.exp));
const mape=(actual,pred)=>mean(actual.map((v,i)=>Math.abs((v-pred[i])/v)))*100;
// Demand holdout uses realized explanatory variables: conditional fit, not a fully ex ante forecast.
const validation={priceMAPE:mape(holdout.map(r=>r.price),holdout.map((r,i)=>Math.exp(dot(priceX(r,60+i),pTrain.beta))*smearing(pTrain))),priceNaiveMAPE:mape(holdout.map(r=>r.price),history.slice(48,60).map(r=>r.price)),demandConditionalMAPE:mape(holdout.map(r=>r.demand),holdout.map(r=>Math.exp(dot(demandX(r),dTrain.beta))*smearing(dTrain))),demandNaiveMAPE:mape(holdout.map(r=>r.demand),history.slice(48,60).map(r=>r.demand))};
function forecasts(){const last=history.at(-1);return Array.from({length:72},(_,h)=>{const i=72+h,month=i%12,year=2026+Math.floor(h/12),income=last.income*Math.pow(1.03,(h+1)/12),substitute=last.substitute*Math.pow(1.02,(h+1)/12),xr=priceX({month},i),lp=dot(xr,priceFit.beta),lev=dot(xr,priceFit.inv.map(r=>dot(r,xr))),spread=1.282*Math.sqrt(priceFit.mse*(1+lev)),price=Math.exp(lp)*smearing(priceFit),r={year,month,price,income,substitute},demand=Math.exp(dot(demandX(r),demandFit.beta))*smearing(demandFit);return {...r,date:`${year}-${String(month+1).padStart(2,'0')}`,priceLow:Math.exp(lp-spread),priceHigh:Math.exp(lp+spread),demand};});}
const forward=forecasts(),weights=[.04,.08,.16,.18,.13,.08,.04,.02,.04,.07,.10,.06];
const annual=Array.from({length:6},(_,i)=>{const yr=2026+i,r=forward.filter(x=>x.year===yr),price=r.reduce((s,x,j)=>s+x.price*weights[j],0),base=root.KATORT?.projections()[i],financial=base?root.KATORT.calculate(2026,{...base,price}):null;return {year:yr,price,low:price*.9,high:price*1.1,demand:r.reduce((s,x)=>s+x.demand,0),financial};});
const A=[[.05,.60,0,0],[.02,.08,.50,0],[.02,.04,.06,.02],[.20,.12,.10,.15]],Iminus=A.map((r,i)=>r.map((v,j)=>(i===j?1:0)-v)),L=inverse(Iminus),f=[0,0,2728000,0],output=L.map(r=>dot(r,f)),valueAdded=A[0].map((_,j)=>1-A.reduce((s,r)=>s+r[j],0)),io={A,L,f,output,valueAdded,totalOutput:output.reduce((s,x)=>s+x,0),totalVA:dot(output,valueAdded),multiplier:L.reduce((s,r)=>s+r[2],0)};
function stats(a){const avg=mean(a),sd=Math.sqrt(a.reduce((s,v)=>s+(v-avg)**2,0)/(a.length-1));return {mean:avg,median:quantile(a,.5),sd,cv:sd/avg,min:Math.min(...a),max:Math.max(...a),p10:quantile(a,.1),p90:quantile(a,.9)};}
const X=history.map(demandX);const vif=Array.from({length:5},(_,h)=>{const j=h+1,fit=ols(X.map(r=>r.filter((_,i)=>i!==j)),X.map(r=>r[j]));return 1/(1-fit.r2);});
const api={history,demandFit,priceFit,validation,forward,annual,io,stats,ols,inverse,vif};root.KATORT_ECON=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);

