'use strict';
(function(root){
const pair=(es,en)=>({es,en});
const swot={strengths:[pair('F1 · 100 ha productivas; 60 propias.','S1 · 100 productive ha; 60 owned.'),pair('F2 · Empaque y frío propios: USD 650,000 netos.','S2 · Owned packing and cooling: USD 650,000 net.'),pair('F3 · EBITDA 2025 de USD 708,000 y cuatro pagos de deuda supuestos realizados.','S3 · USD 708,000 2025 EBITDA and four assumed completed debt payments.')],weaknesses:[pair('D1 · DSCR 1.27×, menor que meta interna 1.30×.','W1 · 1.27× DSCR, below internal 1.30× target.'),pair('D2 · Comprador principal concentra 50% de exportación.','W2 · Largest buyer accounts for 50% of exports.'),pair('D3 · 40 ha rentadas y cobranza supuesta a 45 días.','W3 · 40 leased ha and assumed 45-day collections.')],opportunities:[pair('O1 · Explorar dos compradores adicionales; oportunidad no comprobada.','O1 · Explore two additional buyers; unverified opportunity.'),pair('O2 · Mejorar selección para exportación de 80% a 85%; viabilidad por validar.','O2 · Improve export grade from 80% to 85%; feasibility unverified.'),pair('O3 · Trazabilidad y contratos por calidad para diferenciar oferta.','O3 · Traceability and quality contracts to differentiate supply.')],threats:[pair('A1 · Caída de precio/rendimiento: escenario de estrés no cubre deuda.','T1 · Price/yield decline: stress scenario does not cover debt.'),pair('A2 · Interrupción de agua, bombeo o cadena fría.','T2 · Water, pumping or cold-chain disruption.'),pair('A3 · Retraso de cobranza, rechazo o salida de comprador.','T3 · Late collections, rejects or buyer loss.')]};
const strategies=[['FO',pair('F2 + O3: documentar frío y trazabilidad para negociar por calidad.','S2 + O3: document cooling and traceability to negotiate on quality.'),pair('Operaciones + comercial','Operations + sales'),'60',pair('Registro en 100% de embarques.','Records for 100% of shipments.')],['DO',pair('D2 + O1: incorporar prospectos y reducir concentración sin sacrificar cobranza.','W2 + O1: develop prospects and reduce concentration without sacrificing collections.'),pair('Dirección','Management'),'90',pair('Meta ≤35%; no equivale a ventas aseguradas.','Target ≤35%; does not imply guaranteed sales.')],['FA',pair('F3 + A1: reservar servicio de deuda antes de distribuciones.','S3 + T1: reserve debt service before distributions.'),pair('Finanzas','Finance'),'30',pair('Reserva 2026 USD 28,166.67/mes, validando caja.','2026 reserve USD 28,166.67/month, subject to cash availability.')],['DA',pair('D3 + A3: revisar renta, vencimientos y crédito por comprador.','W3 + T3: review lease, maturities and buyer credit.'),pair('Administración + dirección','Administration + management'),'30',pair('Cartera semanal y condiciones documentadas.','Weekly receivables review and documented terms.')]];
const program=[
pair('M1 · Alta, validación documental, diagnóstico y línea base.','M1 · Onboarding, document validation, diagnosis and baseline.'),pair('M2 · Flujo de caja a 13 semanas y presupuesto por ciclo.','M2 · 13-week cash flow and crop-cycle budget.'),pair('M3 · Márgenes por lote, calibre y comprador; primera revisión trimestral.','M3 · Margins by block, grade and buyer; first quarterly review.'),pair('M4 · Expediente de preparación crediticia y garantías.','M4 · Credit-readiness file and collateral review.'),pair('M5 · Sensibilidad de precio, rendimiento, calidad y cobranza.','M5 · Price, yield, grade and collection sensitivity.'),pair('M6 · Revisión semestral de deuda y actualización del plan.','M6 · Semiannual debt review and plan update.'),pair('M7 · Costos de reposición, riego, frío y mantenimiento.','M7 · Replacement, irrigation, cooling and maintenance costs.'),pair('M8 · Estrategia comercial y concentración de clientes.','M8 · Commercial strategy and buyer concentration.'),pair('M9 · Actualización sectorial y evaluación del siguiente ciclo.','M9 · Sector update and next-cycle evaluation.'),pair('M10 · Preparar pago anual de deuda y presupuesto siguiente.','M10 · Prepare annual debt payment and next budget.'),pair('M11 · Confirmar saldo, liquidez y condiciones de vencimiento.','M11 · Confirm balance, liquidity and maturity terms.'),pair('M12 · Informe anual, cumplimiento del plan y propuesta de siguiente ciclo.','M12 · Annual report, plan review and next-cycle proposal.')];
const documents=[pair('Estados financieros, balanza y conciliaciones bancarias.','Financial statements, trial balance and bank reconciliations.'),pair('Contrato de deuda y estado de cuenta del acreedor.','Loan agreement and lender statement.'),pair('Facturas, cobranza y antigüedad de saldos por comprador.','Invoices, collections and buyer receivables aging.'),pair('Registros de cosecha, clasificación, rechazo y embarques.','Harvest, grading, reject and shipment records.'),pair('Títulos de propiedad, renta, garantías y derechos de agua.','Property titles, leases, collateral and water rights.'),pair('Presupuesto de campo, nómina, fletes e inversión.','Field budget, payroll, freight and capital expenditure.'),pair('Identificación y documentación corporativa en repositorio privado.','Identity and corporate documents in a private repository.')];
const investment={name:pair('Mejora de selección y control de frío','Grading and cold-control upgrade'),capex:120000,discount:.10,cashflows:[48000,55000,60000,60000,60000],assumed:true};
function npv(rate){return -investment.capex+investment.cashflows.reduce((s,v,i)=>s+v/(1+rate)**(i+1),0);}function irr(){let lo=-.9,hi=5;for(let i=0;i<100;i++){const mid=(lo+hi)/2;npv(mid)>0?lo=mid:hi=mid;}return (lo+hi)/2;}function payback(){let total=0;for(let i=0;i<investment.cashflows.length;i++){if(total+investment.cashflows[i]>=investment.capex)return i+(investment.capex-total)/investment.cashflows[i];total+=investment.cashflows[i];}return null;}
const data={swot,strategies,program,documents,investment,npv,irr,payback};root.KATORT_SERVICE=data;if(typeof module!=='undefined')module.exports=data;
})(typeof window!=='undefined'?window:globalThis);

