'use strict';
(function(root){
function loan(c){let b=c.loan.original;return Array.from({length:c.loan.term},(_,i)=>{const opening=b,principal=c.loan.original/c.loan.term,interest=opening*c.loan.rate;b-=principal;return {year:c.loan.start+i,opening,principal,interest,service:principal+interest,closing:Math.max(0,b),completed:i<c.loan.paid};});}
function calculate(c,changes={}){const v={volume:c.volume,price:c.price,unitCost:c.unitCost,fixed:c.fixed,capex:c.capex,wc:c.wc,...changes},d=loan(c)[c.loan.paid-1],revenue=v.volume*v.price,variable=v.volume*v.unitCost,contribution=revenue-variable,ebitda=contribution-v.fixed,ebit=ebitda-c.depreciation,interest=d.interest,tax=Math.max(0,ebit-interest)*c.taxRate,net=ebit-interest-tax,cfads=ebitda-tax-v.capex-v.wc,afterDebt=cfads-d.service,cash=c.openingCash+afterDebt-c.dividends;return {...v,revenue,variable,contribution,ebitda,ebit,interest,tax,net,cfads,service:d.service,principal:d.principal,afterDebt,cash,debt:d.closing,margin:ebitda/revenue,dscr:cfads/d.service,breakeven:v.fixed/(v.price-v.unitCost),operatingCash:ebitda-tax-v.wc-interest};}
function monthly(c,m=calculate(c)){let cash=c.openingCash;return c.weights.map((w,i)=>{const revenue=m.revenue*w,variable=m.variable*c.costWeights[i],fixed=m.fixed/12,capex=i===3?m.capex:0,wc=i===2?m.wc:0,tax=i===11?m.tax:0,interest=i===11?m.interest:0,principal=i===11?m.principal:0,dividends=i===11?c.dividends:0,change=revenue-variable-fixed-capex-wc-tax-interest-principal-dividends;cash+=change;return {month:i+1,revenue,variable,fixed,capex,wc,tax,interest,principal,dividends,change,cash};});}
function balance(c){const m=calculate(c),b=c.balance,assets=m.cash+b.receivables+b.inventory+b.prepaid+b.fixedNet+b.other,liabilities=b.payables+b.accrued+m.debt;return {assets,liabilities,equity:b.equity,currentDebt:Math.min(c.loan.original/c.loan.term,m.debt),longDebt:Math.max(0,m.debt-c.loan.original/c.loan.term),dso:b.receivables/m.revenue*365,dio:b.inventory/m.variable*365,dpo:b.payables/m.variable*365};}
function projections(c){let cash=calculate(c).cash;return Array.from({length:3},(_,i)=>{const k=i+1,f=c.forecast,schedule=loan(c),debt=schedule.find(d=>d.year===2025+k),volume=c.volume*Math.pow(1+f.volume,k),price=c.price*Math.pow(1+f.price,k),unitCost=c.unitCost*Math.pow(1+f.cost,k),fixed=c.fixed*Math.pow(1+f.fixed,k),revenue=volume*price,ebitda=revenue-volume*unitCost-fixed,interest=debt?.interest||0,tax=Math.max(0,ebitda-c.depreciation-interest)*c.taxRate,cfads=ebitda-tax-f.capex-f.wc,service=debt?.service||0,opening=cash;cash+=cfads-service;return {year:2025+k,volume,price,unitCost,fixed,revenue,ebitda,tax,capex:f.capex,wc:f.wc,cfads,service,dscr:service?cfads/service:null,openingCash:opening,cash};});}
function npv(rate,capex,flows){return -capex+flows.reduce((s,v,i)=>s+v/Math.pow(1+rate,i+1),0);}
function irr(capex,flows){let low=-.9,high=10;if(npv(low,capex,flows)*npv(high,capex,flows)>0)return null;for(let i=0;i<100;i++){const mid=(low+high)/2;if(npv(mid,capex,flows)>0)low=mid;else high=mid;}return (low+high)/2;}
function payback(capex,flows){let left=capex;for(let i=0;i<flows.length;i++){if(flows[i]>0&&flows[i]>=left)return i+left/flows[i];left-=flows[i];}return null;}
function inverse(a){const n=a.length,m=a.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]);for(let i=0;i<n;i++){let pivot=i;for(let k=i+1;k<n;k++)if(Math.abs(m[k][i])>Math.abs(m[pivot][i]))pivot=k;[m[i],m[pivot]]=[m[pivot],m[i]];const v=m[i][i];if(Math.abs(v)<1e-10)throw Error('Singular matrix');m[i]=m[i].map(x=>x/v);for(let k=0;k<n;k++)if(k!==i){const f=m[k][i];m[k]=m[k].map((x,j)=>x-f*m[i][j]);}}return m.map(r=>r.slice(n));}
function economics(c){const history=Array.from({length:72},(_,i)=>{const year=2020+Math.floor(i/12),month=i%12+1,t=i-60,activity=100*Math.exp(.0025*t+.03*Math.cos(i*.41)),price=c.price*Math.exp(.0018*t+.13*Math.sin(i*.61)+.04*Math.cos(i*.27));return {year,month,price,activity};});const norm=c.price/(history.slice(60).reduce((s,r)=>s+r.price,0)/12);history.forEach((r,i)=>{r.price*=norm;r.quantity=c.economy.marketVolume/12*Math.exp(c.economy.elasticity*Math.log(r.price/c.price)+c.economy.activityElasticity*Math.log(r.activity/100)+.02*Math.sin(i*1.73));});const X=history.map(r=>[1,Math.log(r.price/c.price),Math.log(r.activity/100)]),Y=history.map(r=>Math.log(r.quantity)),xtx=Array.from({length:3},(_,i)=>Array.from({length:3},(_,j)=>X.reduce((s,r)=>s+r[i]*r[j],0))),inv=inverse(xtx),xty=Array.from({length:3},(_,j)=>X.reduce((s,r,i)=>s+r[j]*Y[i],0)),beta=inv.map(r=>r.reduce((s,v,j)=>s+v*xty[j],0)),residual=Y.map((v,i)=>v-X[i].reduce((s,x,j)=>s+x*beta[j],0)),mean=Y.reduce((s,v)=>s+v,0)/72,sse=residual.reduce((s,v)=>s+v*v,0),sst=Y.reduce((s,v)=>s+(v-mean)**2,0),r2=1-sse/sst;const forecast=Array.from({length:3},(_,i)=>{const year=2026+i,k=i+1,price=c.price*(1+c.economy.priceGrowth)**k,activity=100*(1+c.economy.activityGrowth)**k,quantity=Math.exp(beta[0]+beta[1]*Math.log(price/c.price)+beta[2]*Math.log(activity/100))*12;return {year,price,activity,quantity};});const A=c.economy.A,Iminus=A.map((r,i)=>r.map((v,j)=>(i===j?1:0)-v)),L=inverse(Iminus),revenue=calculate(c).revenue,f=[0,0,revenue,0],output=L.map(r=>r.reduce((s,v,j)=>s+v*f[j],0)),valueAdded=output.map((v,j)=>v*(1-A.reduce((s,r)=>s+r[j],0)));return {history,beta,r2,forecast,A,output,valueAdded,multiplier:output.reduce((s,v)=>s+v,0)/revenue};}
const api={loan,calculate,monthly,balance,projections,npv,irr,payback,inverse,economics};root.ONCE14_MODEL=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window!=='undefined'?window:globalThis);
